import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from 'next/script';
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Script
          src="https://cf.journity.com/collector/journity-anthony.com.js"
          strategy="afterInteractive"
        />
        <Script
          src="https://cf.journity.com/personalizer/journity-anthony.com.min.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
